{% set python_min = python_min|default("3.8") %}
{% set version = "1.7.1" %}

package:
  name: windspharm
  version: {{ version }}

source:
  url: https://github.com/ajdawson/windspharm/archive/v{{ version }}.tar.gz
  sha256: f6bd22f6d32e3381e89855c696159f1a3f41b9588491317f2ed9cfe47b79d24c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pyspharm >=1.0.8

test:
  imports:
    - windspharm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - pytest

about:
  home: http://ajdawson.github.io/windspharm/
  license: MIT
  license_file: license.txt
  summary: 'Python package for performing computations on global wind fields in spherical geometry.'

extra:
  recipe-maintainers:
    - ajdawson
    - ocefpaf
