{% set version = "1.7.1" %}

package:
  name: windspharm
  version: {{ version }}

source:
  url: https://github.com/ajdawson/windspharm/archive/v{{ version }}.tar.gz
  sha256: f6bd22f6d32e3381e89855c696159f1a3f41b9588491317f2ed9cfe47b79d24c

build:
  number: 0
  skip: true  # [win and py3k or win64]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pyspharm

test:
  requires:
    - pytest
  imports:
    - windspharm

about:
  home: http://ajdawson.github.io/windspharm/
  license: MIT
  license_file: license.txt
  summary: 'Python package for performing computations on global wind fields in spherical geometry.'

extra:
  recipe-maintainers:
    - ajdawson
    - ocefpaf
