{% set python_min = python_min|default("3.8") %}
{% set version = "2.0.0" %}

package:
  name: windspharm
  version: {{ version }}

source:
  url: https://github.com/ajdawson/windspharm/archive/v{{ version }}.tar.gz
  sha256: 227d435290c5b2b2709d1d34c97586ffab4c680e81a9c8e03bde4b5f3cab8219

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pyspharm >=1.0.9

test:
  imports:
    - windspharm
  commands:
    - pip check
    - pytest --pyargs windspharm
  requires:
    - pip
    - python {{ python_min }}
    - pytest

about:
  home: http://ajdawson.github.io/windspharm/
  license: MIT
  license_file: license.txt
  summary: 'Python package for performing computations on global wind fields in spherical geometry.'

extra:
  recipe-maintainers:
    - ajdawson
    - ocefpaf
