# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "WNe1pi4ctpPc9zEQpzEIZXr+i2qX5HexfQBOdDQY/yIGfvzG4QPhZmCATErQ74mjvtzF6QDq0dyJfOLO1TgimSQke8m53DS2EsWcwRJSce6DbJBw8qQCklbt8Hhv9+7sK7cdV1M2r6BTfk34SP4PG4CDL39Ql4iTafGOtTcOd8JfDPPzW19LEtWuxpW5TCP0+MwQTGH/X4hWoRMcZuBv7THPPng1bYroDLYiatp4uQc+a5G021x5+bn7OQq1ahrrd2tIVDYNtw5mLNuYtHTmDRW86YDZrmsCDinOrmC5AQLyzHmpVhIpb8O/QtPSj8oTKwN2ZHzfiT4LYPvQeefkEOibVzD72bcRgX9ZsjqUopvwTLMYbLYTgNtxpY/Y6WVtSA9FyabcCS8wAvOLXjtbAIA1CB3m5wUo6Y+c8niQqXpBNPRPEmf8a8H1gGfCHmZNRKGNLhl5snpvxx1W+k8d6OU0BjMvcsDtWWS1wlOTC5nVTiZiiu5y1cBwmibyjQAHbsLKlyCR7CgsfaTlRsH+jOuz/NoenF8NhkoR3ncz+F37AZWh/cA+sbMjnpIsTjdKVapKeltrAznxDk7h1lSJpSmbf0CrGoXm5tlqze3MtTpzHUVq29TR2mwQkrZpXkS2C3tYVs6KhP4EwUPL379K0PPt8UTCIqdARzCIDuyY69k="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
