travis:
  secure:
    BINSTAR_TOKEN: WNe1pi4ctpPc9zEQpzEIZXr+i2qX5HexfQBOdDQY/yIGfvzG4QPhZmCATErQ74mjvtzF6QDq0dyJfOLO1TgimSQke8m53DS2EsWcwRJSce6DbJBw8qQCklbt8Hhv9+7sK7cdV1M2r6BTfk34SP4PG4CDL39Ql4iTafGOtTcOd8JfDPPzW19LEtWuxpW5TCP0+MwQTGH/X4hWoRMcZuBv7THPPng1bYroDLYiatp4uQc+a5G021x5+bn7OQq1ahrrd2tIVDYNtw5mLNuYtHTmDRW86YDZrmsCDinOrmC5AQLyzHmpVhIpb8O/QtPSj8oTKwN2ZHzfiT4LYPvQeefkEOibVzD72bcRgX9ZsjqUopvwTLMYbLYTgNtxpY/Y6WVtSA9FyabcCS8wAvOLXjtbAIA1CB3m5wUo6Y+c8niQqXpBNPRPEmf8a8H1gGfCHmZNRKGNLhl5snpvxx1W+k8d6OU0BjMvcsDtWWS1wlOTC5nVTiZiiu5y1cBwmibyjQAHbsLKlyCR7CgsfaTlRsH+jOuz/NoenF8NhkoR3ncz+F37AZWh/cA+sbMjnpIsTjdKVapKeltrAznxDk7h1lSJpSmbf0CrGoXm5tlqze3MtTpzHUVq29TR2mwQkrZpXkS2C3tYVs6KhP4EwUPL379K0PPt8UTCIqdARzCIDuyY69k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
